#!/usr/bin/env bash
# Route conformance for the Kinetix gateway. (S2 / P1-GW-03)
#
# Asserts two things that no amount of reading gateway.pkl can establish:
#
#   1. EVERY UPSTREAM RESOLVES. Each service url in the GENERATED kong.yml names a host that
#      actually exists on the `kinetix` network. The audit's finding was that not one of them
#      did; the file looked correct and routed to nothing.
#
#   2. NO PUBLIC PATH IS A 404. Every declared route is requested through the gateway and must
#      not come back 404 — the signature of a strip_path that rewrote the resource name away,
#      or of a route pointing at an endpoint the upstream never had.
#
# Driven from the kong.yml the image actually carries, not from a list maintained by hand:
# a route added to gateway.pkl is tested by the next run without anyone remembering to add it.
#
# Usage:  test/route_conformance.sh [base-url]        (default http://localhost:8080)

set -uo pipefail

BASE="${1:-http://localhost:8080}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE="$HERE/../kinetix-infrastructure/compose.yaml"

pass=0; fail=0
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; pass=$((pass+1)); }
bad()  { printf '  \033[31m✗\033[0m %s\n' "$*"; fail=$((fail+1)); }

gw_container() { docker compose -f "$COMPOSE" ps -q kinetix-api-gateway; }

GW="$(gw_container)"
[ -n "$GW" ] || { echo "gateway container is not running: docker compose -f $COMPOSE up -d"; exit 1; }

KONG_YML="$(docker exec "$GW" cat /usr/local/kong/declarative/kong.yml)"

# Extract (url, path...) pairs from the declarative config without a YAML library — the file
# is generated by pkl with a fixed shape, so the indentation is stable.
parse() {
  printf '%s\n' "$KONG_YML" | awk '
    /^- name: /            { svc=substr($0,9) }
    /^  url: /             { url=substr($0,8) }
    /^    - \//            { print svc "\t" url "\t" substr($0,7) }
  '
}

echo "── 1. Every upstream host resolves from inside the gateway"
seen=""
while IFS=$'\t' read -r svc url path; do
  host="$(printf '%s' "$url" | sed -E 's#https?://([^:/]+).*#\1#')"
  case " $seen " in *" $host "*) continue ;; esac
  seen="$seen $host"
  [ "$host" = "127.0.0.1" ] && continue
  if docker exec "$GW" getent hosts "$host" >/dev/null 2>&1; then
    ok "$host resolves"
  else
    bad "$host does NOT resolve — no container answers to this name"
  fi
done < <(parse)

echo
echo "── 2. No declared public path returns 404"
while IFS=$'\t' read -r svc url path; do
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "$BASE$path")"
  case "$code" in
    404) bad "$path -> $code  ($svc)  route declared but nothing serves it" ;;
    000) bad "$path -> no response  ($svc)  gateway unreachable or timed out" ;;
    5*)  bad "$path -> $code  ($svc)  upstream error" ;;
    *)   ok  "$path -> $code  ($svc)" ;;
  esac
done < <(parse)

echo
echo "── 3. The gateway is the only thing on the host"
published="$(docker compose -f "$COMPOSE" config --format json \
  | python3 -c 'import json,sys;d=json.load(sys.stdin);print(sum(len(v.get("ports") or []) for v in d["services"].values()))')"
if [ "$published" = "1" ]; then
  ok "exactly one published port mapping in compose.yaml"
else
  bad "$published published port mappings — expected 1 (the gateway)"
fi

echo
printf '%d passed, %d failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
