version: '3.8'

services:
  gateway:
    build: .
    container_name: kinetix_api_gateway
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_LISTEN=0.0.0.0:8080, 0.0.0.0:8443 ssl
