version: '3.8'

services:
  gateway:
    build: .
    container_name: kinetix_api_gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CATALOG_SERVICE_URL=http://host.docker.internal:8000
      - WAREHOUSE_SERVICE_URL=http://host.docker.internal:3000
      - MATCHING_SERVICE_URL=http://host.docker.internal:4000
